;;; doom-custom-theme.el --- Doom theme powered by Matugen palette -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Author: Generated by Matugen
;; Maintainer:
;; Source: https://github.com/InioX/matugen
;;
;;; Commentary:
;; A dynamically generated Doom Emacs theme using Material You colors from Matugen.
;;
;;; Code:

(require 'doom-themes)

;;
;;; Variables

(defgroup doom-custom-theme nil
  "Options for the `doom-custom' theme."
  :group 'doom-themes)

(defcustom doom-custom-brighter-comments nil
  "If non-nil, comments will be highlighted in more vivid colors."
  :group 'doom-custom-theme
  :type 'boolean)

(defcustom doom-custom-padded-modeline doom-themes-padded-modeline
  "If non-nil, adds a 4px padding to the mode-line.
Can be an integer to determine the exact padding."
  :group 'doom-custom-theme
  :type '(or integer boolean))

;;
;;; Theme definition

(def-doom-theme doom-custom
  "A Doom theme powered by Matugen palette."

  ;; name        default   256       16
  ((bg         '("#000000" nil nil))
   (fg         '("#ffffff" nil nil))

   (bg-alt     '("#000000" nil nil))
   (fg-alt     '("#cccccc" nil nil))

   (base0      '("#000000" nil nil))
   (base1      '("#000000" nil nil))
   (base2      '("#000000" nil nil))
   (base3      '("#000000" nil nil))
   (base4      '("#000000" nil nil))
   (base5      '("#888888" nil nil))
   (base6      '("#000000" nil nil))
   (base7      '("#000000" nil nil))
   (base8      '("#000000" nil nil))

   (white      '("#ffffff" nil nil))
   (grey       '("#cccccc" nil nil))
   (red        '("#ffffff" nil nil))
   (orange     '("#ffffff" nil nil))
   (orange-alt '("#cccccc" nil nil))
   (green      '("#ffffff" nil nil))
   (green-alt  '("#cccccc" nil nil))
   (teal       '("#cccccc" nil nil))
   (yellow     '("#ffffff" nil nil))
   (blue       '("#ffffff" nil nil))
   (dark-blue  '("#cccccc" nil nil))
   (magenta    '("#ffffff" nil nil))
   (violet     '("#ffffff" nil nil))
   (cyan       '("#cccccc" nil nil))
   (dark-cyan  '("#cccccc" nil nil))

   ;; face categories -- these are used by doom-themes
   (highlight      blue)
   (vertical-bar   (doom-darken base0 0.1))
   (selection      (doom-blend blue bg 0.3))
   (builtin        magenta)
   (comments       (if doom-custom-brighter-comments dark-cyan (doom-lighten base5 0.2)))
   (doc-comments   (doom-lighten (if doom-custom-brighter-comments dark-cyan base5) 0.25))
   (constants      green-alt)
   (functions      orange-alt)
   (keywords       blue)
   (methods        teal)
   (operators      fg)
   (type           yellow)
   (strings        green)
   (variables      (doom-lighten magenta 0.4))
   (numbers        magenta)
   (region         (doom-darken bg-alt 0.1))
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    orange)
   (vc-added       green)
   (vc-deleted     red)

   ;; modeline
   (-modeline-pad
    (when doom-custom-padded-modeline
      (if (integerp doom-custom-padded-modeline) doom-custom-padded-modeline 4)))

   (modeline-fg          fg)
   (modeline-fg-alt      (doom-lighten base5 0.3))
   (modeline-bg          (doom-darken bg-alt 0.1))
   (modeline-bg-inactive (doom-darken bg 0.1)))

  ;;;; Base theme face overrides
  (((font-lock-comment-face &override)
    :background (if doom-custom-brighter-comments (doom-lighten bg 0.05) 'unspecified))
   ((line-number &override) :foreground (doom-lighten base5 0.2))
   ((line-number-current-line &override) :foreground "#f9b1da" :weight 'bold)
   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-inactive :foreground modeline-fg-alt
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive)))

   ;;;; css-mode <built-in> / scss-mode
   (css-proprietary-property :foreground orange)
   (css-property             :foreground green)
   (css-selector             :foreground blue)
   ;;;; doom-modeline
   (doom-modeline-bar :background green)
   (doom-modeline-buffer-file :inherit 'mode-line-buffer-id :weight 'bold)
   (doom-modeline-buffer-path :inherit 'mode-line-emphasis :weight 'bold)
   (doom-modeline-buffer-project-root :foreground green :weight 'bold)
   ;;;; elscreen
   (elscreen-tab-other-screen-face :background (doom-darken bg 0.1) :foreground fg-alt)
   ;;;; evil
   (evil-goggles-default-face :inherit 'region :background (doom-blend region bg 0.5))
   ;;;; ivy
   (ivy-current-match :background (doom-blend blue bg 0.2) :distant-foreground base0 :weight 'normal)
   (ivy-minibuffer-match-face-2 :foreground green :weight 'bold)
   ;;;; markdown-mode
   (markdown-markup-face :foreground base5)
   (markdown-header-face :inherit 'bold :foreground red)
   (markdown-code-face :background (doom-lighten bg 0.05))
   ;;;; org-mode
   (org-block :background (doom-darken bg 0.05))
   (org-block-begin-line :foreground comments :background (doom-darken bg 0.05))
   (org-hide :foreground bg)
   ;;;; solaire-mode
   (solaire-mode-line-face
    :inherit 'mode-line
    :background modeline-bg
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (solaire-mode-line-inactive-face
    :inherit 'mode-line-inactive
    :background modeline-bg-inactive
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive))))

  ;;;; Base theme variable overrides
  ())

;;; doom-custom-theme.el ends here
